### ISSUE TITLE
test.py Error

### ISSUE THREAD

**Issue by dreyes15** [angr/angr-doc#149]
Just wanted to let you guys know of an error on the test.py file, currently installed angr on a virtual environment with  pypy using the shell script provided. Upon running the test.py script I receive the following:

Error on line 16 of docs/loading.md: name 'b' is not defined
Traceback (most recent call last):
  File "test.py", line 43, in try_running
    exec line in env
  File "<string>", line 1, in <module>
NameError: name 'b' is not defined
Traceback (most recent call last):
  File "test.py", line 115, in <module>
    tester(arg)
  File "test.py", line 61, in doctest_single
    try_running(line, i)
  File "test.py", line 47, in try_running
    raise Exception('Error on line %d of %s: %s' % (i+1, md_file, e))
Exception: Error on line 16 of docs/loading.md: name 'b' is not defined

**Comment by zardus** [comment]
I think this was fixed sometime in the last week!
