### ISSUE TITLE
`test_examples.test_cmu_binary_bomb` is failing in CI

### ISSUE THREAD

**Issue by twizmwazin** [angr/angr-doc#435]
### Description

```
Traceback (most recent call last):
  File "/__w/angr-doc/angr-doc/build/src/angr-doc/tests/test_examples.py", line 64, in test_cmu_binary_bomb
    exampletest_single("cmu_binary_bomb")  # 3m
  File "/__w/angr-doc/angr-doc/build/src/angr-doc/tests/test_examples.py", line 32, in exampletest_single
    module.test()
  File "/__w/angr-doc/angr-doc/build/src/angr-doc/examples/cmu_binary_bomb/solve.py", line 280, in test
    assert solve_flag_1() == 'Border relations with Canada have never been better.'
  File "/__w/angr-doc/angr-doc/build/src/angr-doc/examples/cmu_binary_bomb/solve.py", line 55, in solve_flag_1
    raise Exception("angr failed to find a path to the solution :(")
Exception: angr failed to find a path to the solution :(
```

### Steps to reproduce the bug

Run CI

### Environment

CI

**Comment by ltfish** [comment]
@twizmwazin See if it's a flaky test.
