### ISSUE TITLE
`test_examples.test_secconquals2016_ropsynth` is failing in CI

### ISSUE THREAD

**Issue by twizmwazin** [angr/angr-doc#437]
### Description

```
Traceback (most recent call last):
  File "/__w/angr-doc/angr-doc/build/src/angr-doc/tests/test_examples.py", line 156, in test_secconquals2016_ropsynth
    exampletest_single("secconquals2016_ropsynth")
  File "/__w/angr-doc/angr-doc/build/src/angr-doc/tests/test_examples.py", line 31, in exampletest_single
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/__w/angr-doc/angr-doc/build/src/angr-doc/examples/secconquals2016_ropsynth/solve.py", line 17, in <module>
    import nose
ModuleNotFoundError: No module named 'nose'
```

### Steps to reproduce the bug

Run CI

### Environment

CI

**Comment by twizmwazin** [comment]
After #456, the error is now:

```
======================================================================
ERROR: test_examples.test_secconquals2016_ropsynth
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/angr-doc/angr-doc/build/src/angr-doc/tests/test_examples.py", line 156, in test_secconquals2016_ropsynth
    exampletest_single("secconquals2016_ropsynth")
  File "/__w/angr-doc/angr-doc/build/src/angr-doc/tests/test_examples.py", line 32, in exampletest_single
    module.test()
  File "/__w/angr-doc/angr-doc/build/src/angr-doc/examples/secconquals2016_ropsynth/solve.py", line 212, in test
    chain = get_gadgets()
  File "/__w/angr-doc/angr-doc/build/src/angr-doc/examples/secconquals2016_ropsynth/solve.py", line 109, in get_gadgets
    good_state = sm.unconstrained[0]
IndexError: list index out of range
```
