### ISSUE TITLE
HackCon 2016 (angry-reverser) does not work

### ISSUE THREAD

**Issue by Manouchehri** [angr/angr-doc#91]
```bash
(angr)angr@c06036219af2:~/angr-dev/angr-doc/examples/hackcon2016_angry-reverser$ python solve.py 
Launching exploration
ERROR   | 2016-09-12 17:20:39,947 | angr.simos | Syscall 101 is not found for arch AMD64
ERROR   | 2016-09-12 17:20:39,950 | angr.simos | Syscall 101 is not found for arch AMD64
Traceback (most recent call last):
  File "solve.py", line 42, in <module>
    assert main() == "HACKCON{VVhYS04ngrY}"
  File "solve.py", line 35, in main
    final = ex.found[0].state
IndexError: list index out of range
Segmentation fault (core dumped)
(angr)angr@c06036219af2:~/angr-dev/angr-doc/examples/hackcon2016_angry-reverser$ pip list
ana (0.02, /home/angr/angr-dev/ana)
angr (5.6.8.22, /home/angr/angr-dev/angr)
angr-management (4.6.6.28, /home/angr/angr-dev/angr-management)
angr-only-z3-custom (4.4.1.post4)
archinfo (5.6.8.22, /home/angr/angr-dev/archinfo)
argparse (1.2.1)
astroid (1.4.8)
atom (0.3.10)
backports.functools-lru-cache (1.2.1)
backports.shutil-get-terminal-size (1.0.0)
backports.ssl-match-hostname (3.5.0.1)
bintrees (2.0.4)
cachetools (1.1.6)
capstone (3.0.4)
cffi (1.8.2)
claripy (5.6.8.22, /home/angr/angr-dev/claripy)
cle (5.6.8.22, /home/angr/angr-dev/cle)
configparser (3.5.0)
cooldict (1.02, /home/angr/angr-dev/cooldict)
coverage (4.2)
decorator (4.0.10)
distribute (0.7.3)
dpkt-fix (1.7)
enaml (0.9.8)
enum34 (1.1.6)
future (0.15.2)
futures (3.0.5)
idalink (0.10, /home/angr/angr-dev/idalink)
ipdb (0.10.1)
ipython (5.1.0)
ipython-genutils (0.1.0)
isort (4.2.5)
kiwisolver (0.1.3)
lazy-object-proxy (1.2.2)
mccabe (0.5.2)
monkeyhex (1.1, /home/angr/angr-dev/monkeyhex)
mulpyplexer (0.07, /home/angr/angr-dev/mulpyplexer)
networkx (1.11)
nose (1.3.7)
nose-timer (0.6.0)
pathlib2 (2.1.0)
pefile (2016.3.28)
pexpect (4.2.1)
pickleshare (0.7.4)
pip (1.5.4)
plumbum (1.6.2)
ply (3.9)
progressbar (2.3)
prompt-toolkit (1.0.7)
ptyprocess (0.5.1)
pycparser (2.14)
pyelftools (0.24)
Pygments (2.1.3)
pylint (1.6.4)
pyvex (5.6.8.22, /home/angr/angr-dev/pyvex)
rpyc (3.3.0)
setuptools (27.1.2)
simplegeneric (0.8.1)
simuvex (5.6.8.22, /home/angr/angr-dev/simuvex)
six (1.10.0)
superstruct (1.0, /home/angr/angr-dev/superstruct)
termcolor (1.1.0)
traitlets (4.3.0)
unicorn (1.0)
wcwidth (0.1.7)
websocket-client (0.37.0)
wrapt (1.10.8)
wsgiref (0.1.2)
```

Pinging @P1kachu (#87).

**Comment by ltfish** [comment]
Segfault? I guess this is because of Z3. Can you please check the call stack trace in the core dump?

**Comment by P1kachu** [comment]
I had the very last version of angr too. I wouldn't have guessed the flag without it working :p

**Comment by Manouchehri** [comment]
Hmm, will try this again later. Odd, I was using the Docker image on Ubuntu 16.04 inside of VirtualBox.

**Comment by ltfish** [comment]
All possible sources of a memory corruption in angr:
- Z3.
- Unicorn support in SimuVEX or Unicorn itself.
- VEX and its Python binding (unlikely).

A core dump should be able to tell you which one is the culprit.

**Comment by Manouchehri** [comment]
I'm no longer able to reproduce this error on my current machine, must have been something to do with my last setup.

Regardless, this isn't an issue in angr-doc.
